export DEBEMAIL=hanhaoxuan@uniontech.com
export DEBFULLNAME=shiroko
export PATH=$PATH:"$HOME/Projects/ShiroDEB/bin"
export DEB_UPLOAD_PATH=$HOME/Check
alias sd="shirodeb"
alias sdi="shirodeb install"
alias sdm="shirodeb make"
alias sdr="shirodeb remove"
alias sds="shirodeb save"
alias sdrmi="shirodeb remove && shirodeb make && shirodeb install"
